class UserService:
    def create_user(self, dto: UserCreateDTO) -> UserResponseDTO: ...
    def get_user(self, user_id: str) -> UserResponseDTO | None: ...
    def list_users(self) -> list[UserResponseDTO]: ...
    def update_user(self, user_id: str, dto: UserUpdateDTO) -> UserResponseDTO | None: ...
    def delete_user(self, user_id: str) -> None: ...
